name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build for Wndows
      run: env GOOS=windows GOARCH=amd64 go build -o build/prisons.exe .
      
    - name: Build for Linux
      run: env GOOS=linux GOARCH=amd64 go build -o build/prisons-linux . 
      
    - name: Build for FreeBSD
      run: env GOOS=freebsd GOARCH=amd64 go build -o build/prisons-freebsd .
      
    - name: Upload windows artifact
      uses: actions/upload-artifact@v2
        with:
          name: prisons.exe
          path: build/prisons.exe
          retention-days: 30
    - name: Upload linux artifact
      uses: actions/upload-artifact@v2
        with:
          name: prisons-linux
          path: build/prisons-linux
          retention-days: 30
    - name: Upload freebsd artifact 
      uses: actions/upload-artifact@v2
        with:
          name: prisons-freebsd
          path: build/prisons-freebsd
          retention-days: 30
